apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: global-super-admin-binding
subjects:
- kind: User
  name: "babamba" # 운영자 유저 이름 (인증서 CN)
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin # 쿠버네티스 내장 최고 권한 Role
  apiGroup: rbac.authorization.k8s.io