apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # base64로 인코딩 필요
  DATABASE_USER: cm9vdA==
  DATABASE_PASSWORD: MTAwNA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DATABASE_HOST: "192.168.120.121"
  DATABASE_PORT: "3306"
  DATABASE_DB_NAME: "employees"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  REDIS_SENTINEL_HOST: "redis-sentinel-service"
  REDIS_SENTINEL_PORT: "26379"
  REDIS_MASTER_NAME: "mymaster"

  REDIS_CACHE_HOST: "redis-cache-service"
  REDIS_CACHE_PORT: "6379"