apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-server
  template:
    metadata:
      labels:
        app: employee-server
    spec:
      serviceAccountName: employee-sa
      containers:
      - name: employee-server
        image: jaewoozzang/employee_server:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: redis-config
        - secretRef:
            name: db-credentials
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: employee-server
  labels:
    app: fastapi-app
spec:
  ports:
  - name: http
    port: 5002
  selector:
    app: employee-server