apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-server
spec:
  selector:
    matchLabels:
      app: employee-server
  template:
    metadata:
      labels:
        app: employee-server
    spec:
      containers:
      - name: employee-server
        image: jaewoozzang/employee_server:v0.7
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: employee-server
spec:
  ports:
    - port: 5002
  selector:
    app: employee-server