apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-server
spec:
  selector:
    matchLabels:
      app: employee-server
  template:
    metadata:
      labels:
        app: employee-server
    spec:
      containers:
      - name: employee-server
        image: jaewoozzang/employee_server:v1.03
        imagePullPolicy: Always
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: redis-config
        - secretRef:
            name: db-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: employee-server
spec:
  ports:
    - port: 5002
  selector:
    app: employee-server