apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-service
spec:
  selector:
    matchLabels:
      app: photo-service
  template:
    metadata:
      labels:
        app: photo-service
    spec:
      containers:
      - name: photo-service
        image: jaewoozzang/photo_service:v0.9
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: photo-data
          mountPath: /app/data
      volumes:
      - name: photo-data
        persistentVolumeClaim:
          claimName: photo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: photo-service
spec:
  ports:
    - port: 5003
  selector:
    app: photo-service