apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-service
  template:
    metadata:
      labels:
        app: photo-service
    spec:
      serviceAccountName: photo-sa
      containers:
      - name: photo-service
        image: jaewoozzang/photo_service:v1.0
        ports:
        - containerPort: 5003
        volumeMounts:
        - name: photo-storage
          mountPath: /app/static/uploads
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: photo-storage
        persistentVolumeClaim:
          claimName: photo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: photo-service
  labels:
    app: fastapi-app
spec:
  ports:
    - name: http
      port: 5003
  selector:
    app: photo-service