apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: employee-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: photo-sa
  namespace: default